# Generated by Django 4.1.1 on 2022-10-24 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('p_price', models.FloatField(max_length=20)),
                ('p_rating', models.FloatField(default='1', max_length=20)),
                ('p_details', models.TextField(max_length=40)),
                ('ca_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_ca_id', to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('w_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='W_c_id', to='home.customer')),
                ('p_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='w_p_id', to='item.products')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('review', models.FloatField(max_length=20)),
                ('c_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='R_c_id', to='home.customer')),
                ('p_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='R_p_id', to='item.products')),
                ('star', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='star', to='item.products')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cart_totalAmmount', models.FloatField(max_length=20)),
                ('ca_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_p_ca_id', to='home.category')),
            ],
        ),
    ]
