# Generated by Django 4.1.1 on 2022-10-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customer_c_name_remove_customer_c_password_and_more'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ca_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='p_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='c_id',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_p_c_id', to='home.customer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.products'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='c_id',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='w_c_id', to='home.customer'),
        ),
    ]
