# Generated by Django 4.1.1 on 2022-10-24 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customer_c_name_remove_customer_c_password_and_more'),
        ('item', '0002_remove_cart_ca_id_remove_review_p_id_cart_c_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sc_id',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_sca_id', to='home.sub_category'),
        ),
    ]
