# Generated by Django 4.1.1 on 2022-10-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_rating',
            field=models.FloatField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='star', to='product.products'),
        ),
    ]
