# Generated by Django 4.1.1 on 2022-10-24 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ca_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ca_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('sc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sc_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_address', models.TextField(max_length=80)),
                ('c_phoneNum', models.CharField(max_length=20)),
                ('c_name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='c_name', to=settings.AUTH_USER_MODEL)),
                ('c_password', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='c_password', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
