# Generated by Django 4.1.1 on 2022-10-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_address', models.TextField(max_length=80)),
                ('c_phoneNum', models.CharField(max_length=20)),
            ],
        ),
    ]
