# Generated by Django 4.1.1 on 2022-10-21 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_customer_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='c_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
