# Generated by Django 4.1.1 on 2022-10-21 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_customer_c_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='c_password',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='c_password', to=settings.AUTH_USER_MODEL),
        ),
    ]
