# Generated by Django 4.1.1 on 2022-10-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customer_c_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
