# Generated by Django 4.1.1 on 2022-10-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('w_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='W_c_id', to='home.customer')),
            ],
        ),
    ]
