# Generated by Django 4.1.1 on 2022-10-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
