# Generated by Django 4.1.1 on 2022-10-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('home', '0011_delete_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pa_type', models.CharField(max_length=20)),
                ('pa_confirm', models.CharField(max_length=20)),
                ('c_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_c_id', to='home.customer')),
                ('cart_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_c_id', to='product.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.IntegerField(primary_key=True, serialize=False)),
                ('o_total', models.FloatField(max_length=20)),
                ('o_quantity', models.IntegerField()),
                ('cart_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o_c_id', to='product.cart')),
                ('p_id', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o_p_id', to='product.product')),
            ],
        ),
    ]
